#!/bin/sh

if [ -f /.flatpak-info ]; then

    echo "Flatpak environment detected"
    echo "Running Inside Sandbox"
    export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID}"
    exec zypak-wrapper /app/share/chatbot-client/chatbot-client

else 
    echo "Not a flatpak environment"
    /usr/share/chatbot-client/chatbot-client
fi





